// <auto-generated />
using System;
using MechanicShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MechanicShopAPI.Migrations
{
    [DbContext(typeof(MechanicShopContext))]
    [Migration("20251030211601_AddMultiTenancyInfrastructure")]
    partial class AddMultiTenancyInfrastructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MechanicShopAPI.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "ScheduledDate");

                    b.HasIndex("TenantId", "Status");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LaborCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("MileageAtService")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("PartsCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TechnicianName")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("TenantId", "ServiceDate");

                    b.ToTable("ServiceRecords");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CtaButtonText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CtaSubtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CtaTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeroImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("HeroSubtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("MondayFridayHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryCtaText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SatisfactionRate")
                        .HasColumnType("integer");

                    b.Property<string>("SaturdayHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecondaryCtaText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1Feature1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1Feature2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1Feature3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1Feature4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service1ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Service1Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2Feature1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2Feature2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2Feature3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2Feature4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service2ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Service2Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3Feature1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3Feature2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3Feature3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3Feature4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Service3ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Service3Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SundayHours")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VehiclesServiced")
                        .HasColumnType("integer");

                    b.Property<string>("WhyFeature1Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature1Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature2Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature2Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature3Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature3Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature4Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyFeature4Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearsExperience")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Auto Street",
                            BusinessName = "Precision Automotive",
                            City = "City",
                            CtaButtonText = "Book Appointment",
                            CtaSubtitle = "Schedule your service appointment today",
                            CtaTitle = "Ready to Get Started?",
                            Email = "info@mechanic.com",
                            HeroSubtitle = "Expert Service for Your Vehicle",
                            HeroTitle = "PRECISION\nAUTOMOTIVE\nCARE",
                            MondayFridayHours = "8am - 6pm",
                            Phone = "(555) 123-4567",
                            PrimaryCtaText = "Schedule Service",
                            SatisfactionRate = 98,
                            SaturdayHours = "9am - 4pm",
                            SecondaryCtaText = "Our Services",
                            Service1Description = "Oil changes, filter replacements, fluid checks, and comprehensive inspections to keep your vehicle running smoothly.",
                            Service1Feature1 = "Oil & Filter Change",
                            Service1Feature2 = "Brake Inspection",
                            Service1Feature3 = "Tire Rotation",
                            Service1Feature4 = "Fluid Top-ups",
                            Service1Title = "Routine Maintenance",
                            Service2Description = "Advanced diagnostic tools and expert technicians to identify and resolve any mechanical or electrical issues.",
                            Service2Feature1 = "Computer Diagnostics",
                            Service2Feature2 = "Engine Repair",
                            Service2Feature3 = "Transmission Service",
                            Service2Feature4 = "Electrical Systems",
                            Service2Title = "Diagnostics & Repair",
                            Service3Description = "Enhance your vehicle's performance with professional tuning, upgrades, and custom modifications.",
                            Service3Feature1 = "Engine Tuning",
                            Service3Feature2 = "Suspension Upgrades",
                            Service3Feature3 = "Exhaust Systems",
                            Service3Feature4 = "Brake Upgrades",
                            Service3Title = "Performance Upgrades",
                            State = "State",
                            SundayHours = "Closed",
                            Tagline = "Expert Service for Your Vehicle",
                            UpdatedAt = new DateTime(2025, 10, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            VehiclesServiced = 5000,
                            WhyFeature1Description = "ASE-certified mechanics with decades of combined experience",
                            WhyFeature1Title = "Expert Technicians",
                            WhyFeature2Description = "We use only OEM and premium aftermarket parts",
                            WhyFeature2Title = "Quality Parts",
                            WhyFeature3Description = "No hidden fees, detailed estimates before any work begins",
                            WhyFeature3Title = "Transparent Pricing",
                            WhyFeature4Description = "All services backed by our comprehensive warranty",
                            WhyFeature4Title = "Warranty Coverage",
                            YearsExperience = 25,
                            ZipCode = "12345"
                        });
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessAddress")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IntegrationSettings")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxCustomers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxVehicles")
                        .HasColumnType("integer");

                    b.Property<string>("MediaStoragePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Plan")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("StorageLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<long>("StorageUsedBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Plan");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessAddress = "123 Main Street",
                            City = "Springfield",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "contact@precision-auto.com",
                            MaxCustomers = 1000,
                            MaxUsers = 10,
                            MaxVehicles = 2000,
                            MediaStoragePath = "/tenants/precision-auto/media",
                            Name = "Precision Automotive",
                            Phone = "(555) 123-4567",
                            Plan = 2,
                            Slug = "precision-auto",
                            State = "IL",
                            Status = 0,
                            StorageLimitBytes = 5368709120L,
                            StorageUsedBytes = 0L,
                            ZipCode = "62701"
                        },
                        new
                        {
                            Id = 2,
                            BusinessAddress = "456 Industrial Blvd",
                            City = "Chicago",
                            Country = "US",
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "info@acme-motors.com",
                            MaxCustomers = 500,
                            MaxUsers = 5,
                            MaxVehicles = 1000,
                            MediaStoragePath = "/tenants/acme-motors/media",
                            Name = "ACME Motors & Repair",
                            Phone = "(555) 987-6543",
                            Plan = 1,
                            Slug = "acme-motors",
                            State = "IL",
                            Status = 0,
                            StorageLimitBytes = 5368709120L,
                            StorageUsedBytes = 0L,
                            ZipCode = "60601"
                        },
                        new
                        {
                            Id = 3,
                            BusinessAddress = "789 Speedway Drive",
                            City = "Indianapolis",
                            Country = "US",
                            CreatedAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "service@speedway.com",
                            MaxCustomers = 10000,
                            MaxUsers = 50,
                            MaxVehicles = 20000,
                            MediaStoragePath = "/tenants/speedway-service/media",
                            Name = "Speedway Service Center",
                            Phone = "(555) 555-0123",
                            Plan = 3,
                            Slug = "speedway-service",
                            State = "IN",
                            Status = 0,
                            StorageLimitBytes = 5368709120L,
                            StorageUsedBytes = 0L,
                            ZipCode = "46204"
                        });
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Appointment", b =>
                {
                    b.HasOne("MechanicShopAPI.Models.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicShopAPI.Models.Tenant", "Tenant")
                        .WithMany("Appointments")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicShopAPI.Models.Vehicle", "Vehicle")
                        .WithMany("Appointments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tenant");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Customer", b =>
                {
                    b.HasOne("MechanicShopAPI.Models.Tenant", "Tenant")
                        .WithMany("Customers")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.ServiceRecord", b =>
                {
                    b.HasOne("MechanicShopAPI.Models.Tenant", "Tenant")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicShopAPI.Models.Vehicle", "Vehicle")
                        .WithMany("ServiceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Vehicle", b =>
                {
                    b.HasOne("MechanicShopAPI.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MechanicShopAPI.Models.Tenant", "Tenant")
                        .WithMany("Vehicles")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Customer", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Tenant", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Customers");

                    b.Navigation("ServiceRecords");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("MechanicShopAPI.Models.Vehicle", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
