CREATE TABLE IF NOT EXISTS "SiteSettings" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_SiteSettings" PRIMARY KEY AUTOINCREMENT,
    "BusinessName" TEXT NOT NULL,
    "Tagline" TEXT NOT NULL,
    "Address" TEXT NOT NULL,
    "City" TEXT NOT NULL,
    "State" TEXT NOT NULL,
    "ZipCode" TEXT NOT NULL,
    "Phone" TEXT NOT NULL,
    "Email" TEXT NOT NULL,
    "MondayFridayHours" TEXT NOT NULL,
    "SaturdayHours" TEXT NOT NULL,
    "SundayHours" TEXT NOT NULL,
    "VehiclesServiced" INTEGER NOT NULL,
    "SatisfactionRate" INTEGER NOT NULL,
    "YearsExperience" INTEGER NOT NULL,
    "HeroTitle" TEXT NOT NULL,
    "HeroSubtitle" TEXT NOT NULL,
    "PrimaryCtaText" TEXT NOT NULL,
    "SecondaryCtaText" TEXT NOT NULL,
    "Service1Title" TEXT NOT NULL,
    "Service1Description" TEXT NOT NULL,
    "Service1Feature1" TEXT NOT NULL,
    "Service1Feature2" TEXT NOT NULL,
    "Service1Feature3" TEXT NOT NULL,
    "Service1Feature4" TEXT NOT NULL,
    "Service2Title" TEXT NOT NULL,
    "Service2Description" TEXT NOT NULL,
    "Service2Feature1" TEXT NOT NULL,
    "Service2Feature2" TEXT NOT NULL,
    "Service2Feature3" TEXT NOT NULL,
    "Service2Feature4" TEXT NOT NULL,
    "Service3Title" TEXT NOT NULL,
    "Service3Description" TEXT NOT NULL,
    "Service3Feature1" TEXT NOT NULL,
    "Service3Feature2" TEXT NOT NULL,
    "Service3Feature3" TEXT NOT NULL,
    "Service3Feature4" TEXT NOT NULL,
    "WhyFeature1Title" TEXT NOT NULL,
    "WhyFeature1Description" TEXT NOT NULL,
    "WhyFeature2Title" TEXT NOT NULL,
    "WhyFeature2Description" TEXT NOT NULL,
    "WhyFeature3Title" TEXT NOT NULL,
    "WhyFeature3Description" TEXT NOT NULL,
    "WhyFeature4Title" TEXT NOT NULL,
    "WhyFeature4Description" TEXT NOT NULL,
    "CtaTitle" TEXT NOT NULL,
    "CtaSubtitle" TEXT NOT NULL,
    "CtaButtonText" TEXT NOT NULL,
    "LogoUrl" TEXT,
    "HeroImageUrl" TEXT,
    "UpdatedAt" TEXT NOT NULL
);
